#! /usr/bin/python

import argparse
import os
import keyring
import modules.git
import modules.android
import smtplib

from modules import message

from modules.actions import FlagAction
from ansi2html import Ansi2HTMLConverter

app_name = 'deliver_python_app'

def get_password():
    #print "Please enter your password:"
    os.system("stty -echo")
    password = raw_input("Password: ")
    os.system("stty echo")
    print "\n"
    return password

def process(args, msg):
    msg.append_html("<h1>Vokal Delivery</h1>")

    return msg

def start_request(args):

    username = ''
    while not username or username == '':
        username = raw_input("Username: ")

    password = keyring.get_password(app_name, username)

    if not password or password == '':
        password = get_password()

    try:

        msg = message.Message()
        msg = process(args, msg)
        msg = modules.android.process(args, msg)
        msg = modules.git.process(args, msg)

        msg.send(username, password)

        keyring.set_password(app_name, username, password)
    except smtplib.SMTPAuthenticationError:
        print 'Clearing keychain'
        #Clear the keyring for this user
        keyring.set_password(app_name, username, '')
        print 'Please try again or press Ctrl-C'
        start_request(args, filepath)


if __name__ == '__main__':
    os.system("stty echo")
    parser = argparse.ArgumentParser(description="Build Delivery Utility", epilog='Will automatically look for bin/*-debug.apk and bin/*-release.apk files.  These files are sent with a message via gmail to the recipients')

    modules.android.setup_args(parser);
    modules.git.setup_args(parser);
    parser.add_argument(dest='email', nargs="+", help='A list of email addresses')

    args = parser.parse_args()
    start_request(args)
